server:
  port: 9090

spring:
  application:
    name: product-data-service
  zipkin:
    base-url: http://localhost:9411
  sleuth:
      sampler:
        percentage: 1.0

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/